//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EktronCrawler.EktronWeb.MetaDataApi {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MetadataSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseDataOfCustomAttribute))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseDataOfContentMetaData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomAttribute[]))]
    public partial class Metadata : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private AuthenticationHeader authenticationHeaderValueField;
        
        private RequestInfoParameters requestInfoParametersValueField;
        
        private System.Threading.SendOrPostCallback AddMetaDataTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteMetadataTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetContentMetadataListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetContentMetadataList1OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMetaDataTypesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMetadataTypeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Metadata() {
            this.Url = global::EktronCrawler.Properties.Settings.Default.EktronCrawler_EktronWeb_MetaDataApi_Metadata;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthenticationHeader AuthenticationHeaderValue {
            get {
                return this.authenticationHeaderValueField;
            }
            set {
                this.authenticationHeaderValueField = value;
            }
        }
        
        public RequestInfoParameters RequestInfoParametersValue {
            get {
                return this.requestInfoParametersValueField;
            }
            set {
                this.requestInfoParametersValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddMetaDataTypeCompletedEventHandler AddMetaDataTypeCompleted;
        
        /// <remarks/>
        public event DeleteMetadataTypeCompletedEventHandler DeleteMetadataTypeCompleted;
        
        /// <remarks/>
        public event GetContentMetadataListCompletedEventHandler GetContentMetadataListCompleted;
        
        /// <remarks/>
        public event GetContentMetadataList1CompletedEventHandler GetContentMetadataList1Completed;
        
        /// <remarks/>
        public event GetMetaDataTypesCompletedEventHandler GetMetaDataTypesCompleted;
        
        /// <remarks/>
        public event GetMetadataTypeCompletedEventHandler GetMetadataTypeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("RequestInfoParametersValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddMetaDataType", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddMetaDataType(ref ContentMetaData metaDataItem) {
            object[] results = this.Invoke("AddMetaDataType", new object[] {
                        metaDataItem});
            metaDataItem = ((ContentMetaData)(results[0]));
        }
        
        /// <remarks/>
        public void AddMetaDataTypeAsync(ContentMetaData metaDataItem) {
            this.AddMetaDataTypeAsync(metaDataItem, null);
        }
        
        /// <remarks/>
        public void AddMetaDataTypeAsync(ContentMetaData metaDataItem, object userState) {
            if ((this.AddMetaDataTypeOperationCompleted == null)) {
                this.AddMetaDataTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddMetaDataTypeOperationCompleted);
            }
            this.InvokeAsync("AddMetaDataType", new object[] {
                        metaDataItem}, this.AddMetaDataTypeOperationCompleted, userState);
        }
        
        private void OnAddMetaDataTypeOperationCompleted(object arg) {
            if ((this.AddMetaDataTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddMetaDataTypeCompleted(this, new AddMetaDataTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("RequestInfoParametersValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteMetadataType", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteMetadataType(long MetadataId) {
            this.Invoke("DeleteMetadataType", new object[] {
                        MetadataId});
        }
        
        /// <remarks/>
        public void DeleteMetadataTypeAsync(long MetadataId) {
            this.DeleteMetadataTypeAsync(MetadataId, null);
        }
        
        /// <remarks/>
        public void DeleteMetadataTypeAsync(long MetadataId, object userState) {
            if ((this.DeleteMetadataTypeOperationCompleted == null)) {
                this.DeleteMetadataTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteMetadataTypeOperationCompleted);
            }
            this.InvokeAsync("DeleteMetadataType", new object[] {
                        MetadataId}, this.DeleteMetadataTypeOperationCompleted, userState);
        }
        
        private void OnDeleteMetadataTypeOperationCompleted(object arg) {
            if ((this.DeleteMetadataTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteMetadataTypeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("RequestInfoParametersValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetContentMetadataList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CustomAttribute[] GetContentMetadataList(long ContentId) {
            object[] results = this.Invoke("GetContentMetadataList", new object[] {
                        ContentId});
            return ((CustomAttribute[])(results[0]));
        }
        
        /// <remarks/>
        public void GetContentMetadataListAsync(long ContentId) {
            this.GetContentMetadataListAsync(ContentId, null);
        }
        
        /// <remarks/>
        public void GetContentMetadataListAsync(long ContentId, object userState) {
            if ((this.GetContentMetadataListOperationCompleted == null)) {
                this.GetContentMetadataListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetContentMetadataListOperationCompleted);
            }
            this.InvokeAsync("GetContentMetadataList", new object[] {
                        ContentId}, this.GetContentMetadataListOperationCompleted, userState);
        }
        
        private void OnGetContentMetadataListOperationCompleted(object arg) {
            if ((this.GetContentMetadataListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetContentMetadataListCompleted(this, new GetContentMetadataListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("RequestInfoParametersValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.WebMethodAttribute(MessageName="GetContentMetadataList1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetContentMetadataList with preview", RequestElementName="GetContentMetadataList with preview", RequestNamespace="http://tempuri.org/", ResponseElementName="GetContentMetadataList with previewResponse", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("GetContentMetadataList with previewResult")]
        public CustomAttribute[] GetContentMetadataList(long ContentId, bool preview) {
            object[] results = this.Invoke("GetContentMetadataList1", new object[] {
                        ContentId,
                        preview});
            return ((CustomAttribute[])(results[0]));
        }
        
        /// <remarks/>
        public void GetContentMetadataList1Async(long ContentId, bool preview) {
            this.GetContentMetadataList1Async(ContentId, preview, null);
        }
        
        /// <remarks/>
        public void GetContentMetadataList1Async(long ContentId, bool preview, object userState) {
            if ((this.GetContentMetadataList1OperationCompleted == null)) {
                this.GetContentMetadataList1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetContentMetadataList1OperationCompleted);
            }
            this.InvokeAsync("GetContentMetadataList1", new object[] {
                        ContentId,
                        preview}, this.GetContentMetadataList1OperationCompleted, userState);
        }
        
        private void OnGetContentMetadataList1OperationCompleted(object arg) {
            if ((this.GetContentMetadataList1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetContentMetadataList1Completed(this, new GetContentMetadataList1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("RequestInfoParametersValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMetaDataTypes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ContentMetaData[] GetMetaDataTypes(string OrderBy) {
            object[] results = this.Invoke("GetMetaDataTypes", new object[] {
                        OrderBy});
            return ((ContentMetaData[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMetaDataTypesAsync(string OrderBy) {
            this.GetMetaDataTypesAsync(OrderBy, null);
        }
        
        /// <remarks/>
        public void GetMetaDataTypesAsync(string OrderBy, object userState) {
            if ((this.GetMetaDataTypesOperationCompleted == null)) {
                this.GetMetaDataTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMetaDataTypesOperationCompleted);
            }
            this.InvokeAsync("GetMetaDataTypes", new object[] {
                        OrderBy}, this.GetMetaDataTypesOperationCompleted, userState);
        }
        
        private void OnGetMetaDataTypesOperationCompleted(object arg) {
            if ((this.GetMetaDataTypesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMetaDataTypesCompleted(this, new GetMetaDataTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("RequestInfoParametersValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMetadataType", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ContentMetaData GetMetadataType(long Id) {
            object[] results = this.Invoke("GetMetadataType", new object[] {
                        Id});
            return ((ContentMetaData)(results[0]));
        }
        
        /// <remarks/>
        public void GetMetadataTypeAsync(long Id) {
            this.GetMetadataTypeAsync(Id, null);
        }
        
        /// <remarks/>
        public void GetMetadataTypeAsync(long Id, object userState) {
            if ((this.GetMetadataTypeOperationCompleted == null)) {
                this.GetMetadataTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMetadataTypeOperationCompleted);
            }
            this.InvokeAsync("GetMetadataType", new object[] {
                        Id}, this.GetMetadataTypeOperationCompleted, userState);
        }
        
        private void OnGetMetadataTypeOperationCompleted(object arg) {
            if ((this.GetMetadataTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMetadataTypeCompleted(this, new GetMetadataTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class RequestInfoParameters : System.Web.Services.Protocols.SoapHeader {
        
        private int contentLanguageField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public int ContentLanguage {
            get {
                return this.contentLanguageField;
            }
            set {
                this.contentLanguageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CmsDataOfCustomAttribute))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomAttribute))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class BaseDataOfCustomAttribute {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomAttribute))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class CmsDataOfCustomAttribute : BaseDataOfCustomAttribute {
        
        private long idField;
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomAttribute : CmsDataOfCustomAttribute {
        
        private long propertyValueIdField;
        
        private string nameField;
        
        private object valueField;
        
        private CustomAttributeValueTypes valueTypeField;
        
        private bool isRequiredField;
        
        private int languageField;
        
        private int tagTypeField;
        
        private bool isListField;
        
        private bool doesAtrributeExistField;
        
        /// <remarks/>
        public long PropertyValueId {
            get {
                return this.propertyValueIdField;
            }
            set {
                this.propertyValueIdField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public CustomAttributeValueTypes ValueType {
            get {
                return this.valueTypeField;
            }
            set {
                this.valueTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsRequired {
            get {
                return this.isRequiredField;
            }
            set {
                this.isRequiredField = value;
            }
        }
        
        /// <remarks/>
        public int Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        public int TagType {
            get {
                return this.tagTypeField;
            }
            set {
                this.tagTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsList {
            get {
                return this.isListField;
            }
            set {
                this.isListField = value;
            }
        }
        
        /// <remarks/>
        public bool DoesAtrributeExist {
            get {
                return this.doesAtrributeExistField;
            }
            set {
                this.doesAtrributeExistField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum CustomAttributeValueTypes {
        
        /// <remarks/>
        String,
        
        /// <remarks/>
        Boolean,
        
        /// <remarks/>
        Numeric,
        
        /// <remarks/>
        Date,
        
        /// <remarks/>
        Notification,
        
        /// <remarks/>
        Category,
        
        /// <remarks/>
        CategoryProperties,
        
        /// <remarks/>
        SelectList,
        
        /// <remarks/>
        MultiSelectList,
        
        /// <remarks/>
        ThreadedDiscussion,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CmsDataOfContentMetaData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContentMetaData))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class BaseDataOfContentMetaData {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContentMetaData))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class CmsDataOfContentMetaData : BaseDataOfContentMetaData {
        
        private long idField;
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ContentMetaData : CmsDataOfContentMetaData {
        
        private string textField;
        
        private string nameField;
        
        private ContentMetadataDataType dataTypeField;
        
        private string defaultValueField;
        
        private bool requiredField;
        
        private ContentMetadataType typeField;
        
        private bool isEditableField;
        
        private string separatorField;
        
        private bool caseSensitiveField;
        
        private bool removeDuplicateField;
        
        private bool isSearchAllowedField;
        
        private bool isDisplayableField;
        
        private int languageField;
        
        private string selectableTextField;
        
        private bool allowMultipleField;
        
        private bool isSelectableOnlyField;
        
        private bool metaDisplayEEField;
        
        private MetaDataType metaDataObjectTypeField;
        
        /// <remarks/>
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public ContentMetadataDataType DataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
            }
        }
        
        /// <remarks/>
        public string DefaultValue {
            get {
                return this.defaultValueField;
            }
            set {
                this.defaultValueField = value;
            }
        }
        
        /// <remarks/>
        public bool Required {
            get {
                return this.requiredField;
            }
            set {
                this.requiredField = value;
            }
        }
        
        /// <remarks/>
        public ContentMetadataType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsEditable {
            get {
                return this.isEditableField;
            }
            set {
                this.isEditableField = value;
            }
        }
        
        /// <remarks/>
        public string Separator {
            get {
                return this.separatorField;
            }
            set {
                this.separatorField = value;
            }
        }
        
        /// <remarks/>
        public bool CaseSensitive {
            get {
                return this.caseSensitiveField;
            }
            set {
                this.caseSensitiveField = value;
            }
        }
        
        /// <remarks/>
        public bool RemoveDuplicate {
            get {
                return this.removeDuplicateField;
            }
            set {
                this.removeDuplicateField = value;
            }
        }
        
        /// <remarks/>
        public bool IsSearchAllowed {
            get {
                return this.isSearchAllowedField;
            }
            set {
                this.isSearchAllowedField = value;
            }
        }
        
        /// <remarks/>
        public bool IsDisplayable {
            get {
                return this.isDisplayableField;
            }
            set {
                this.isDisplayableField = value;
            }
        }
        
        /// <remarks/>
        public int Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        public string SelectableText {
            get {
                return this.selectableTextField;
            }
            set {
                this.selectableTextField = value;
            }
        }
        
        /// <remarks/>
        public bool AllowMultiple {
            get {
                return this.allowMultipleField;
            }
            set {
                this.allowMultipleField = value;
            }
        }
        
        /// <remarks/>
        public bool IsSelectableOnly {
            get {
                return this.isSelectableOnlyField;
            }
            set {
                this.isSelectableOnlyField = value;
            }
        }
        
        /// <remarks/>
        public bool MetaDisplayEE {
            get {
                return this.metaDisplayEEField;
            }
            set {
                this.metaDisplayEEField = value;
            }
        }
        
        /// <remarks/>
        public MetaDataType MetaDataObjectType {
            get {
                return this.metaDataObjectTypeField;
            }
            set {
                this.metaDataObjectTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum ContentMetadataDataType {
        
        /// <remarks/>
        Text,
        
        /// <remarks/>
        Number,
        
        /// <remarks/>
        Byte,
        
        /// <remarks/>
        Double,
        
        /// <remarks/>
        Float,
        
        /// <remarks/>
        Integer,
        
        /// <remarks/>
        Long,
        
        /// <remarks/>
        Short,
        
        /// <remarks/>
        Date,
        
        /// <remarks/>
        Boolean,
        
        /// <remarks/>
        SingleSelect,
        
        /// <remarks/>
        MultiSelect,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum ContentMetadataType {
        
        /// <remarks/>
        HtmlTag,
        
        /// <remarks/>
        MetaTag,
        
        /// <remarks/>
        CollectionSelector,
        
        /// <remarks/>
        ListSummarySelector,
        
        /// <remarks/>
        ContentSelector,
        
        /// <remarks/>
        ImageSelector,
        
        /// <remarks/>
        LinkSelector,
        
        /// <remarks/>
        FileSelector,
        
        /// <remarks/>
        MenuSelector,
        
        /// <remarks/>
        UserSelector,
        
        /// <remarks/>
        SearchableProperty,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum MetaDataType {
        
        /// <remarks/>
        Normal,
        
        /// <remarks/>
        ProductAttribute,
        
        /// <remarks/>
        Tags,
        
        /// <remarks/>
        Categories,
        
        /// <remarks/>
        Trackback,
        
        /// <remarks/>
        Ping,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class AuthenticationHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string usernameField;
        
        private string passwordField;
        
        private string domainField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Domain {
            get {
                return this.domainField;
            }
            set {
                this.domainField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AddMetaDataTypeCompletedEventHandler(object sender, AddMetaDataTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddMetaDataTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddMetaDataTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ContentMetaData metaDataItem {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ContentMetaData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void DeleteMetadataTypeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetContentMetadataListCompletedEventHandler(object sender, GetContentMetadataListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetContentMetadataListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetContentMetadataListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomAttribute[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomAttribute[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetContentMetadataList1CompletedEventHandler(object sender, GetContentMetadataList1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetContentMetadataList1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetContentMetadataList1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomAttribute[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomAttribute[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetMetaDataTypesCompletedEventHandler(object sender, GetMetaDataTypesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMetaDataTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMetaDataTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ContentMetaData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ContentMetaData[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetMetadataTypeCompletedEventHandler(object sender, GetMetadataTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMetadataTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMetadataTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ContentMetaData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ContentMetaData)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591